---

- hosts: toolsserverlabo
  gather_facts: no
  vars:
    ansible_ssh_private_key_file_host_path: /home/{{ansible_user}}/.ssh/id_rsa_{{inventory_hostname}}
  tasks:

    - ping:

    - debug:
        msg: "{{ variable_in_vault }}"

  vars_files:
    - "{{vault_file_path}}"
